import base64
import subprocess
from pathlib import Path
import sys


cpp_file = sys.argv[1]
subprocess.run(['g++', '-std=c++17', '-O2',
                cpp_file, '-o', Path(cpp_file).stem])

ascii_bin = ""

with open(Path(cpp_file).stem, 'rb') as f:
    ascii_bin = f.read()

ascii_bin = base64.b85encode(ascii_bin)
ascii_bin = str(ascii_bin, encoding='utf-8')

original_code = ""

with open(cpp_file, 'r') as f:
    original_code = f.read()

generated_code = Path(cpp_file).stem + ".py"

with open(generated_code, 'w') as f:
    f.write("# This code is generated by [Atcoder_base64](https://github.com/kyomukyomupurin/AtCoder_base64)\n# Original source code : \n\n")
    f.write("\"\"\"\n" + original_code + "\n\"\"\"\n\n")
    f.write("import base64\nimport subprocess\n\n\nexe_bin = \"" + ascii_bin +
            "\"\n\nexe_bin = base64.b85decode(exe_bin)\n\nwith open(\"./kyomu\", \'wb\') as f:\n    f.write(exe_bin)\n\nsubprocess.run([\"chmod +x ./kyomu\"], shell=True)\nsubprocess.run([\"./kyomu\"], shell=True)")
